import test from 'node:test';
import assert from 'node:assert/strict';
import {concurrencyView, availableQuota} from './concurrency.mjs';
const fixture=()=>({scheduler_mode:'balanced',snapshots:[{auth_id:'a',eligible:true},{auth_id:'b',eligible:true}],concurrency:{enabled:true,lifecycle_observed:true,active:2,waiting:1,max_per_credential:2,wait_seconds:10,queue_policy:'fifo_per_credential',credentials:{a:{active:2,limit:2,credential_key:'auth:a',waiting:1},b:{active:0,limit:2,credential_key:'auth:b'}},recent_rejections:[]}});
test('sticky queue can coexist with idle pool capacity',()=>{const view=concurrencyView(fixture());assert.equal(view.free,2);assert.equal(view.capacity,4);assert.equal(view.waiting,1);assert.equal(view.full,1);assert.equal(view.title,'有请求正在排队');assert.match(view.description,/绑定凭据/);});
test('aliases count once and unusable credentials add no free capacity',()=>{const state=fixture();state.concurrency.credentials.alias={...state.concurrency.credentials.a};let view=concurrencyView(state,['a']);assert.equal(view.known,2);assert.equal(view.capacity,4);assert.equal(view.free,0);assert.equal(view.eligible,1);});
test('historical rejection totals do not show current congestion',()=>{const state=fixture();state.concurrency.waiting=0;state.concurrency.active=0;state.concurrency.credentials.a.active=0;state.concurrency.rejected=76;const view=concurrencyView(state);assert.equal(view.title,'等待调用');assert.equal(view.tone,'neutral');assert.equal(view.rejected,76);});
test('serial primary busy is shown even if another credential is idle',()=>{const state=fixture();state.scheduler_mode='serial';state.serial_active_auth_id='a';state.concurrency.waiting=0;const view=concurrencyView(state);assert.equal(view.title,'当前凭据已满载');assert.equal(view.free,2);assert.match(view.description,/其他凭据空闲也不分担/);});
test('disabled or unobserved protection does not claim safe capacity',()=>{const state=fixture();state.concurrency.lifecycle_observed=false;assert.equal(concurrencyView(state).free,null);state.concurrency.enabled=false;assert.equal(concurrencyView(state).capacity,null);});

test('unavailable credentials never look like an idle usable pool',()=>{const state=fixture();state.concurrency.waiting=0;state.concurrency.active=0;const view=concurrencyView(state,[]);assert.equal(view.free,0);assert.equal(view.title,'暂无可用凭据');assert.equal(view.tone,'warning');});

test('on-demand cache stays usable until native eligibility changes',()=>{const cached={eligible:true,fresh:false};assert.equal(availableQuota(cached,true),true);assert.equal(availableQuota(cached,false),false);assert.equal(availableQuota({...cached,eligible:false},true),false);});
test('provider cooldown and blocked auth add no usable capacity',()=>{const now=Date.now();const account={eligible:true,fresh:true,adq:{provider_retry_at:new Date(now+60000).toISOString()}};assert.equal(availableQuota(account,true,now),false);assert.equal(availableQuota({...account,adq:null,auth_health:{blocked:true}},true,now),false);assert.equal(availableQuota(account,true,now+61000),true);});
